const Homeproduct = [
    {
        id: 1,
        name: 'product1',
        price: 26,
        image: 'image/p1.webp',
        category: 'tv',
        type: 'new',
    },
    {
        id: 2,
        name: 'product2',
        price: 96,
        image: 'image/p2.webp',
        category: 'laptop',
        type: 'new',
    },
    {
        id: 3,
        name: 'product3',
        price: 236,
        image: 'image/p3.webp',
        category: 'watch',
        type: 'new',
    },
    {
        id: 4,
        name: 'product4',
        price: 636,
        image: 'image/p9.jpg',
        category: 'laptop',
        type: 'new',
    },
    {
        id: 5,
        name: 'product5',
        price: 98,
        image: 'image/p4.webp',
        category: 'speaker',
        type: 'featured',
    },
    {
        id: 6,
        name: 'product6',
        price: 59,
        image: 'image/p5.webp',
        category: 'electronics',
        type: 'featured',
    },
    {
        id: 7,
        name: 'product7',
        price: 956,
        image: 'image/p10.jpg',
        category: 'headphone',
        type: 'featured',
    },
    {
        id: 8,
        name: 'product8',
        price: 389,
        image: 'image/p11.jpg',
        category: 'electronics',
        type: 'featured',
    },
    {
        id: 9,
        name: 'product9',
        price: 67,
        image: 'image/p6.webp',
        category: 'phone',
        type: 'top',
    },
    {
        id: 10,
        name: 'product10',
        price: 76,
        image: 'image/p7.webp',
        category: 'speaker',
        type: 'top',
    },
    {
        id: 11,
        name: 'product11',
        price: 87,
        image: 'image/p8.webp',
        category: 'speaker',
        type: 'top',
    },
    {
        id: 12,
        name: 'product12',
        price: 807,
        image: 'image/p12.jpg',
        category: 'speaker',
        type: 'top',
    },
];

export default Homeproduct;
